ACTIONS = ['encrypt', 'decrypt', 'break']
DATA_TO_SAVE = ['message', 'key', 'file_name', 'radio_message_way', 'radio_language']
DATA_TO_CLEAR = ['message', 'key']
RADIO_MESSAGE_WAY_VALUES = ['text', 'file']
RADIO_LANGUAGE_VALUES = ['ru', 'en']
